#!/bin/zsh

histdb-top () {
    zsh-histdb-init
    local field
    local join
    local table

    argv=(${1:-cmd} "${@:2}")

    case $1 in
        dir)
            field=places.dir
            join='places.rowid = history.place_id'
            table=places
            ;;

        cmd|*)
            field=commands.argv
            join='commands.rowid = history.command_id'
            table=commands
            ;;
    esac

    zsh-histdb-query \
      -header "select count(*) as count, places.host, $field as cmd
              from history
                left join commands
                  on history.command_id=commands.rowid
                left join places
                  on history.place_id=places.rowid
                group by
                  places.host,
                  $field
                order by count(*)"
}

histdb-top "$@"

